name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: GitVersion
        id: gitversion
        uses: PoshCode/Actions/gitversion@v1
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore && echo ${{ steps.gitversion.outputs.LegacySemVerPadded }} > ${{github.workspace}}/VERSION.txt
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Display version
        run: |
          echo $SEMVER > VERSION.txt
      - name: Upload the Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: GameHelper-${{ matrix.os }}
          path: GameHelper/bin/Release/net5.0
